# 1. H2 ?? ??? (?? ????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. ???? DB ??? ??? ?? ??, ??? ?? H2 ??? DB(testdb) ??! ?
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# 3. ?? ?? ?? (???? ???? ??? ???? ???? ??) ?
server.port=${PORT:8080}

# 4. Entity ???? ?? ????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# 5. ???? SQL? ??? ??? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true